# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\static\preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreferencesWidget(object):
    def setupUi(self, PreferencesWidget):
        PreferencesWidget.setObjectName("PreferencesWidget")
        PreferencesWidget.setWindowModality(QtCore.Qt.NonModal)
        PreferencesWidget.resize(561, 179)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreferencesWidget.sizePolicy().hasHeightForWidth())
        PreferencesWidget.setSizePolicy(sizePolicy)
        PreferencesWidget.setMinimumSize(QtCore.QSize(400, 123))
        self.select_file_button = QtWidgets.QPushButton(PreferencesWidget)
        self.select_file_button.setGeometry(QtCore.QRect(390, 40, 151, 23))
        self.select_file_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_file_button.setObjectName("select_file_button")
        self.play_sound_check_box = QtWidgets.QCheckBox(PreferencesWidget)
        self.play_sound_check_box.setGeometry(QtCore.QRect(20, 40, 231, 21))
        self.play_sound_check_box.setObjectName("play_sound_check_box")
        self.soon_label = QtWidgets.QLabel(PreferencesWidget)
        self.soon_label.setGeometry(QtCore.QRect(180, 130, 221, 31))
        self.soon_label.setObjectName("soon_label")
        self.actual_file = QtWidgets.QLineEdit(PreferencesWidget)
        self.actual_file.setEnabled(False)
        self.actual_file.setGeometry(QtCore.QRect(270, 41, 121, 20))
        self.actual_file.setText("")
        self.actual_file.setAlignment(QtCore.Qt.AlignCenter)
        self.actual_file.setObjectName("actual_file")

        self.retranslateUi(PreferencesWidget)
        QtCore.QMetaObject.connectSlotsByName(PreferencesWidget)

    def retranslateUi(self, PreferencesWidget):
        _translate = QtCore.QCoreApplication.translate
        PreferencesWidget.setWindowTitle(_translate("PreferencesWidget", "Preferencias"))
        self.select_file_button.setText(_translate("PreferencesWidget", "Seleccionar archivo..."))
        self.play_sound_check_box.setText(_translate("PreferencesWidget", "Reproducir sonido al encontrar sniper (beta)"))
        self.soon_label.setText(_translate("PreferencesWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Más opciones próximamente</span></p></body></html>"))
